# Generated by Django 3.2.9 on 2022-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighs', '0004_auto_20220105_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
