# Generated by Django 3.2.9 on 2022-01-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighs', '0009_auto_20220111_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='business_name',
            new_name='name',
        ),
    ]
